Repository lacework/terraform-provider-lacework, pull requests merged in 2021-01, with the labels that each got.

#53 docs: adding more documentation about GCP resources
  website/docs/r/integration_gcp_at.html.markdown
  website/docs/r/integration_gcp_cfg.html.markdown
  website/docs/r/integration_gcr.html.markdown
Labels: documentation

#54 ci: send slack notifications to team alias ⭐
  .circleci/config.yml
  website/docs/r/integration_gcp_at.html.markdown
  website/docs/r/integration_gcp_cfg.html.markdown
Labels: ci

#55 Release v0.2.8
  CHANGELOG.md
  RELEASE_NOTES.md
  VERSION
  go.mod
  go.sum
  lacework/version.go
  vendor/github.com/lacework/go-sdk/api/version.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/gopkg.in/yaml.v2/LICENSE
  vendor/gopkg.in/yaml.v2/encode.go
  vendor/gopkg.in/yaml.v2/writerc.go
  vendor/gopkg.in/yaml.v3/.travis.yml
  vendor/gopkg.in/yaml.v3/LICENSE
  vendor/gopkg.in/yaml.v3/NOTICE
  vendor/gopkg.in/yaml.v3/README.md
  vendor/gopkg.in/yaml.v3/apic.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/emitterc.go
  vendor/gopkg.in/yaml.v3/encode.go
  vendor/gopkg.in/yaml.v3/go.mod
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/gopkg.in/yaml.v3/readerc.go
  vendor/gopkg.in/yaml.v3/resolve.go
  vendor/gopkg.in/yaml.v3/scannerc.go
  vendor/gopkg.in/yaml.v3/sorter.go
  vendor/gopkg.in/yaml.v3/writerc.go
  vendor/gopkg.in/yaml.v3/yaml.go
  vendor/gopkg.in/yaml.v3/yamlh.go
  vendor/gopkg.in/yaml.v3/yamlprivateh.go
  vendor/modules.txt
Labels: release

#60 docs: fix typo in aws_ct website resource
  website/docs/r/integration_aws_ct.html.markdown
Labels: documentation
